[server]
host = "127.0.0.1"
port = 8080

[log]
level = "debug"
format = "pretty"

[database]
url = "postgresql://postgres:password@localhost:5432/auth-service_dev"

[redis]
url = "redis://localhost:6379"
